name: continuum
channels:
  - defaults
  - conda-forge
dependencies:
  - matplotlib
  - numpy
  - numpy-base
  - pandas
  - python
  - scikit-learn
  - scipy
  - pip
  - opencv
  - pip:
    - "git+https://github.com/scaleapi/nucleus-python-client.git"
